### ISSUE TITLE
Note saving doesn't work with some locales

### ISSUE THREAD

**Issue by gdonisi** [certified84/AudioNote#2]
Hi, saving a note with English as phone language work, but the app crashes when I use some other languages, like Italian.
I think this is because of some locales use #,## instead of #.## for decimals

<details>
<summary>Error Log</summary>
2022-02-15 11:17:03.673 31044-31044/com.certified.audionote E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.certified.audionote, PID: 31044
    java.lang.NumberFormatException: For input string: "0,01"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at com.certified.audionote.utils.UtilKt.roundOffDecimal(Util.kt:112)
        at com.certified.audionote.ui.EditNoteFragment.stopRecording(EditNoteFragment.kt:434)
        at com.certified.audionote.ui.EditNoteFragment.onClickWhenIdIsZero(EditNoteFragment.kt:295)
        at com.certified.audionote.ui.EditNoteFragment.onClick(EditNoteFragment.kt:198)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7666)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
</details>

**Comment by gdonisi** [comment]
Unfortunately, I'm not very familiar with Kotlin 😢
I can contribute by translating the app in my language, but there are some things that need to be changed first.
Some strings are hardcoded ("Developer", "Contribute" in the settings page; "Just now" in the note date, etc.) so they need to be in the strings.xml file.
Also, I think that some strings should be marked as non-translatable, for example "default_theme", "key_theme" and others.
What do you think?

**Comment by certified84** [comment]
Hi @gdonisi I totally agree with you. I'll make those changes (I.e put hardcoded strings in string.XML) and let you know when I'm done

**Comment by certified84** [comment]
@gdonisi I just made those changes. Kindly check it out on the v0.1.4 branch
